import { Food } from "./app/shared/model/Food";

export const sample_foods:Food[]=[
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 300,
    favorite: false,
    origins: ['italy'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 200,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 220,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 130,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 90,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 280,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 125,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: "🤍🤍🤍🤍🤍",
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 230,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: "",
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'9',
    name: 'Hydrabadi Chicken Biryani',
    price: 320,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: "",
    imageUrl: 'assets/food-9.jpg',
    tags: ['Lunch','Dinner'],
  },
  {
    id:'10',
    name: 'Chole Bhature',
    price: 95,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: "",
    imageUrl: 'assets/food-10.jpg',
    tags: ['FastFood','Lunch'],
  },
  {
    id:'11',
    name: 'Pav Bhaji',
    price: 80,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: "",
    imageUrl: 'assets/food-11.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id:'12',
    name: 'Masala Dosa',
    price: 90,
    cookTime: '45-50',
    favorite: false,
    origins: ['south indian'],
    stars: "",
    imageUrl: 'assets/food-12.jpg',
    tags: ['FastFood','Lunch'],
  },
  {
    id:'13',
    name: 'Veg Noodles',
    price: 100,
    cookTime: '20-30',
    favorite: false,
    origins: ['chinese'],
    stars: "",
    imageUrl: 'assets/food-13.jpg',
    tags: ['FastFood','Lunch'],
  },
]
